### ISSUE TITLE
IDEA 15 can not run benchmark

### ISSUE THREAD

**Issue by blacklion** [artyushov/idea-jmh-plugin#17] opened 2015-11-04 21:41 UTC
Compilation fails with message like

Error:java: java.lang.IllegalStateException: Mismatched format for the line: benchmarks.SinCos.mathSinCos_m===,===benchmarks.generated.SinCos_mathSinCos_m.mathSinCos_m===,===Throughput===,===1====,===[]===,===[5]===,===[5 s]===,===[]===,===[10]===,===[10 s]===,===[]===,===[1]===,===[]===,===[]===,===[]===,===[]===,===[]===,===[]===,===[]===,===[10000]===,===[]

**Comment by artyushov** [comment] 2016-04-15 21:38
If the issue is still relevant for, can you provide a minimal reproducible case for me? I have no problems running simple benchmarks from Intellij 15.

**Comment by stokito** [comment] 2020-10-13 19:30
Closing it as could not reproduce

**Closed by stokito** 2020-10-13 19:30 UTC
